# Change these first
owner: adrianocortes # Your GitHub organization or username, where this repository lives
repo: TrinusTech # The name of this repository

sites:
  - name: ProdAPIAuthsService
    url: https://prodapiauthservice.azurewebsites.net/swagger/index.html
  - name: ProdAPIBilletService
    url: https://prodapibilletservice.azurewebsites.net/swagger/index.html
  - name: ProdAPIFavorecidos
    url: https://prodapifavorecidos.azurewebsites.net/swagger/index.html
  - name: ProdAPIMypropertiesService
    url: https://prodapimypropertiesservice.azurewebsites.net/swagger/index.html
  - name: ProdAPIOnboardingService
    url: https://prodapionboardingservice.azurewebsites.net/swagger/index.html
  - name: prodapitedservice
    url: https://prodapitedservice.azurewebsites.net/swagger/index.html
  - name: ProdAPITotalsService
    url: https://prodapitotalsservice.azurewebsites.net/swagger/index.html
  - name: ProdAPIUserService
    url: https://prodapiuserservice.azurewebsites.net/swagger/index.html
  - name: ProdAPIWebhookService
    url: https://prodapiwebhookservice.azurewebsites.net/swagger/index.html
  - name: Trinus.CO
    url: https://trinus.co
    __dangerous__insecure: true
  - name: TrinuStore
    url: http://trinustore.trinus.co
  - name: Trinus Investimentos
    url: http://trinusinvestimentos.com.br
  - name: Trinus - API Originação
    url: http://apioriginacao.trinus.co
  - name: Trinus - API FaqAtendimento
    url: http://apifaqatendimento.trinus.co
  - name: Trinus - FaqAtendimento
    url: http://faqatendimento.trinus.co
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.trinus.co
  baseUrl: /TrinusTech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TrinusTech
  introTitle: ab
  introMessage: bc
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
